spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    loadbalancer:
      retry:
        enabled: true
        max-retries-on-same-service-instance: 3
        max-retries-on-next-service-instance: 3
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/v1/customer/**, /v3/api-docs/customer-service
          filters:
            - RewritePath=/v3/api-docs/customer-service, /v3/api-docs
            - RemoveRequestHeader=Cookie  # Remove headers as necessary
            - PreserveHostHeader=true
            - AddRequestHeader=Cache-Control, no-cache   # Ensure caching headers are correct
        #          metadata:
        #            roles: customer
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/v1/admin/**, /v3/api-docs/admin-service
          filters:
            - RewritePath=/v3/api-docs/admin-service, /v3/api-docs
            - RemoveRequestHeader=Cookie  # Remove headers as necessary
            - PreserveHostHeader=true
            - AddRequestHeader=Cache-Control, no-cache   # Ensure caching headers are correct
        #          metadata:
        #            roles: admin
        - id: discovery-server
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/online-shop
          jwk-set-uri: http://keycloak:8080/realms/online-shop/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
#  pattern:
#    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
#    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [%X{traceId:-},%X{spanId:-},${spring.application.name}] [%thread] %logger{36} - %msg%n"
  level:
    zipkin2.reporter: INFO
    io.micrometer.tracing: INFO  # Enable debug logging for tracing
    org.springframework.boot.actuate.autoconfigure.tracing: INFO
    root: info
    org.springframework.cloud: info
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: info
#    org.springframework.web.security: DEBUG
server:
  port: 8080


keycloak:
  auth-server-url: http://keycloak:8080/
  realm: online-shop
  resource: api-gateway
  credentials:
    secret: Clw1mu6bHKVCttQs0IwNZJ0DngXRRgHQ
  use-resource-role-mappings: true

#zipkin
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs/customer-service
        name: Customer Service API
      - url: /v3/api-docs/admin-service
        name: Admin Service API