server:
  port: 8080
spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: REACTIVE

  cloud:
    loadbalancer:
      retry:
        enabled: true
        max-retries-on-same-service-instance: 3
        max-retries-on-next-service-instance: 3
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/v1/customer/**, /v3/api-docs/customer-service
          filters:
            - RewritePath=/v3/api-docs/customer-service, /v3/api-docs
            - RemoveRequestHeader=Cookie  # Remove headers as necessary
            - PreserveHostHeader=true
            - AddRequestHeader=Cache-Control, no-cache   # Ensure caching headers are correct
        #          metadata:
        #            roles: customer
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/v1/admin/**, /v3/api-docs/admin-service
          filters:
            - RewritePath=/v3/api-docs/admin-service, /v3/api-docs
            - RemoveRequestHeader=Cookie  # Remove headers as necessary
            - PreserveHostHeader=true
            - AddRequestHeader=Cache-Control, no-cache   # Ensure caching headers are correct
        #          metadata:
        #            roles: admin
        - id: discovery-server
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://discovery-server:8761
          predicates:
            - Path=/eureka/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/online-shop
          jwk-set-uri: http://keycloak:8080/realms/online-shop/protocol/openid-connect/certs
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    zipkin2.reporter: DEBUG
    io.micrometer.tracing: DEBUG  # Enable debug logging for tracing
    org.springframework.boot.actuate.autoconfigure.tracing: DEBUG
    com.example: DEBUG
    org.springframework.cloud: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: INFO
  #    org.springframework.web.security: DEBUG
  #  pattern:
  #    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

  #    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
  #  logback:
  #    appender:
  #      loki:
  #        class: com.github.loki4j.logback.Loki4jAppender
  #        name: LOKI
  #        endpoint: http://loki:3100/loki/api/v1/push
  #        logEvents: INFO,ERROR,WARN,DEBUG
  #        batchSize: 100
  #        batchTimeMs: 5000
  #    root:
  #      level: INFO
  #      appender-ref:
  #        - ref: CONSOLE
  #        - ref: LOKI
  #    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
  #    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  include-application-name: false



keycloak:
  auth-server-url: http://keycloak:8080/
  realm: online-shop
  resource: api-gateway
  credentials:
    secret: UL0vFHKmOQM9lRUEU8WPv7tesMm2c0NL
  use-resource-role-mappings: true

#zipkin
management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            request: true
  observations:
    key-values:
      application: api-gateway
  zipkin:
    tracing:
      endpoint: http://zipkin-all-in-one:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs/customer-service
        name: Customer Service API
      - url: /v3/api-docs/admin-service
        name: Admin Service API